In [1]:
!unzip "/content/drive/My Drive/Deep Learning/Datasets/mobile-price-classification.zip"

Archive:  /content/drive/My Drive/Deep Learning/Datasets/mobile-price-classification.zip
  inflating: test.csv                
  inflating: train.csv               


In [0]:
import pandas as pd
import numpy as np

In [0]:
Dataset=pd.read_csv('/content/train.csv')

In [49]:
Dataset.head()
#print(train.price_range.unique())
#print(train.shape)

battery_power  blue  clock_speed  ...  touch_screen  wifi  price_range
0            842     0          2.2  ...             0     1            1
1           1021     1          0.5  ...             1     0            2
2            563     1          0.5  ...             1     0            2
3            615     1          2.5  ...             0     0            2
4           1821     1          1.2  ...             1     0            1

[5 rows x 21 columns]

In [73]:
#print(Dataset.columns)
Dataset_y=Dataset[['price_range']]
print(len(Dataset_y))
l=np.zeros((2000,4))
row=0
for i in Dataset_y['price_range']:
  l[row,i]=1
  row+=1
print(l)
Dataset_y=pd.DataFrame(l)

2000
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 ...
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]]


In [0]:
Dataset_x=Dataset.drop(columns=['price_range'])
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(Dataset_x,Dataset_y,test_size = 0.1)

In [75]:
from keras.models import Sequential
from keras.layers import Dense
model=Sequential()
model.add(Dense(16, input_dim=20, activation='relu'))
model.add(Dense(12, activation='relu'))
model.add(Dense(4, activation='softmax'))
model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_6 (Dense)              (None, 16)                336       
_________________________________________________________________
dense_7 (Dense)              (None, 12)                204       
_________________________________________________________________
dense_8 (Dense)              (None, 4)                 52        
Total params: 592
Trainable params: 592
Non-trainable params: 0
_________________________________________________________________


In [0]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [79]:
model.fit(x_train,y_train,batch_size=10, epochs=50)

Epoch 1/50
1800/1800 [==============================] - 0s 129us/step - loss: 5.7290 - accuracy: 0.4811
Epoch 2/50
1800/1800 [==============================] - 0s 117us/step - loss: 4.7161 - accuracy: 0.4650
Epoch 3/50
1800/1800 [==============================] - 0s 124us/step - loss: 3.9149 - accuracy: 0.4928
Epoch 4/50
1800/1800 [==============================] - 0s 118us/step - loss: 3.8622 - accuracy: 0.4733
Epoch 5/50
1800/1800 [==============================] - 0s 116us/step - loss: 4.3541 - accuracy: 0.4750
Epoch 6/50
1800/1800 [==============================] - 0s 116us/step - loss: 3.5838 - accuracy: 0.4628
Epoch 7/50
1800/1800 [==============================] - 0s 113us/step - loss: 3.6375 - accuracy: 0.4761
Epoch 8/50
1800/1800 [==============================] - 0s 129us/step - loss: 3.0685 - accuracy: 0.4789
Epoch 9/50
1800/1800 [==============================] - 0s 113us/step - loss: 3.4495 - accuracy: 0.4883
Epoch 10/50
1800/1800 [==============================] - 0s 116u

In [95]:
y_pred=model.predict(x_test,batch_size=10)
l=np.zeros((len(y_test),4))
row=0
for i in range(0,len(y_pred)):
    #print(y_pred[i])
    maxval=0
    maxindex=0
    for j in y_pred[i]:
      c=0
      if j>maxval:
        maxval=j
        maxindex=c
    l[row,maxindex]=1
    row+=1
print(l)

[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0.

In [0]:
def maxelement(arr): 
      
    # get number of rows and columns 
    no_of_rows = len(arr) 
    no_of_column = len(arr[0]) 
      
    for i in range(no_of_rows): 
          
        # Initialize max1 to 0 at beginning 
        # of finding max element of each row 
        max1 = 0
        for j in range(no_of_column): 
            if arr[i][j] > max1 : 
                max1 = arr[i][j] 
                  
        # print maximum element of each row 
        print(max1)

In [84]:

_, accuracy = model.evaluate(x_test, y_test)
print('Accuracy: %.2f' % (accuracy*100))

200/200 [==============================] - 0s 110us/step
Accuracy: 47.00
